---
params:
  ano: ""
  duckdb_path: ""
---

```{r}
con <- duckdb::dbConnect(duckdb::duckdb(), params$duckdb_path)
ano <- params$ano
```

# Anexo III — Dados Mundiais de Energia {-}

Fonte: Agência Internacional de Energia (IEA)

## Oferta de Energia por Fonte

```{r}
tab <- dplyr::tbl(con, "grafico_comp_oferta_energia_fonte") |>
  dplyr::collect() |>
  dplyr::mutate(ano = as.character(ano))

anos <- unique(tab$ano)
anos_comparacao <- sort(anos[anos != max(anos, na.rm = TRUE)])

plots <- purrr::map(
  anos_comparacao,
  \(.ano) {
    tab_filtrada <- tab |> dplyr::filter(ano %in% c(.ano, max(ano, na.rm = TRUE)))
    ggplot2::ggplot(tab_filtrada) +
      ggplot2::geom_col(
        ggplot2::aes(x = variavel, y = valores, fill = ano),
        position = "dodge"
      ) +
      ggplot2::theme_minimal()
  }
)

benCorrido::create_dropdown_plot(
  plots = plots,
  params = anos_comparacao,
  label = "Ano de comparação",
  fig_width = 11,
  fig_height = 3,
  dropdown_width = "200px"
)

```

```{r}
htmltools::tags$script(src = "../js/fix_slider.js")
```

