### Consumo Final por Fonte

::: {.panel-tabset}

## Valor absoluto

```{r}
#| tbl-cap: 'Consumo Final por Fonte. Valores absolutos. Unidade: 10³ tep.'
#| label: tbl-consumo-final-fonte-absoluto

benCorrido::tab_consumo_final_fonte(con, .tipo = "Absoluto", lang = "en")
benCorrido::gerar_botoes_download(tab_name = "tab_consumo_final_fonte", .tipo_dado = "Absoluto")
```

```{r}
#| label: fig-consumo-final-fonte-absoluto
#| fig-cap: 'Consumo Final por Fonte. Valores absolutos. Outros: Carvão Mineral, Outras Fontes Primárias, Biodiesel, Gás de Coqueria, Coque de Carvão Mineral, Carvão Vegetal , Álcool Etílico, Alcatrão.'
linha <- benCorrido::grafico_consumo_final_fonte(con, .tipo_dado = "Absoluto", .tipo_grafico = "linha", lang = "en")
area <- benCorrido::grafico_consumo_final_fonte(con, .tipo_dado = "Absoluto", .tipo_grafico = "area", lang = "en")

benCorrido::criar_carrossel(area, linha)
```

## Valor percentual

```{r}
#| tbl-cap: 'Consumo Final por Fonte. Valores percentuais. Unidade: (%).'
#| label: tbl-consumo-final-fonte-percentual

benCorrido::tab_consumo_final_fonte(con, .tipo = "Percentual", lang = "en")
benCorrido::gerar_botoes_download(tab_name = "tab_consumo_final_fonte", .tipo_dado = "Percentual")
```


```{r}
#| label: fig-consumo-final-fonte-percentual
#| fig-cap: 'Consumo Final por Fonte. Valores percentuais. Outros: Carvão Mineral, Outras Fontes Primárias, Biodiesel, Gás de Coqueria, Coque de Carvão Mineral, Carvão Vegetal , Álcool Etílico, Alcatrão.'
linha <- benCorrido::grafico_consumo_final_fonte(con, .tipo_dado = "Percentual", .tipo_grafico = "linha", lang = "en")
area <- benCorrido::grafico_consumo_final_fonte(con, .tipo_dado = "Percentual", .tipo_grafico = "area", lang = "en")

benCorrido::criar_carrossel(area, linha)
```

:::



### Consumo Final por Setor

::: {.panel-tabset}

## Valor absoluto

```{r}
#| label: tbl-consumo-final-setor-absoluto
#| tbl-cap: 'Consumo Final por Setor. Valores absolutos. Unidade: 10³ tep.'

benCorrido::tab_consumo_final_setor(con, .tipo_dado = "Absoluto", lang = "en")
benCorrido::gerar_botoes_download(tab_name = "tab_consumo_final_setor", .tipo_dado = "Absoluto")
```

```{r}
#| label: fig-consumo-final-setor-absoluto
#| fig-cap: 'Consumo Final por Setor. Valores absolutos. Outros: Comercial, Público, Consumo Não-Identificado.'

linha <- benCorrido::grafico_consumo_final_setor(con, .tipo_dado = "Absoluto", .tipo_grafico = "linha", lang = "en")
area <- benCorrido::grafico_consumo_final_setor(con, .tipo_dado = "Absoluto", .tipo_grafico = "area", lang = "en")

benCorrido::criar_carrossel(area, linha)
```

## Valor percentual

```{r}
#| label: tbl-consumo-final-setor-percentual
#| tbl-cap: 'Consumo Final por Setor. Valores percentuais. Unidade: (%).'

benCorrido::tab_consumo_final_setor(con, .tipo = "Percentual", lang = "en")
benCorrido::gerar_botoes_download(tab_name = "tab_consumo_final_setor", .tipo_dado = "Percentual")
```


```{r}
#| label: fig-consumo-final-setor-percentual
#| fig-cap: 'Consumo Final por Setor. Valores percentuais. Outros: Comercial, Público, Consumo Não-Identificado.'

linha <- benCorrido::grafico_consumo_final_setor(con, .tipo_dado = "Percentual", .tipo_grafico = "linha", lang = "en")
area <- benCorrido::grafico_consumo_final_setor(con, .tipo_dado = "Percentual", .tipo_grafico = "area", lang = "en")

benCorrido::criar_carrossel(area, linha)
```

:::


### Consumo Final Energético por Fonte

::: {.panel-tabset}

## Valor absoluto

```{r}
#| label: tbl-consumo-final-energetico-fonte-absoluto
#| tbl-cap: 'Consumo Final Energético por Fonte. Valores absolutos. Unidade: 10³ tep.'

benCorrido::tab_consumo_final_energetico_fonte(con, .tipo = "Absoluto", lang = "en")
benCorrido::gerar_botoes_download(tab_name = "tab_consumo_final_energetico_fonte", .tipo_dado = "Absoluto")
```

## Valor percentual

```{r}
#| label: tbl-consumo-final-energetico-fonte-percentual
#| tbl-cap: 'Consumo Final Energético por Fonte. Valores percentuais. Unidade: (%).'

benCorrido::tab_consumo_final_energetico_fonte(con, .tipo = "Percentual", lang = "en")
benCorrido::gerar_botoes_download(tab_name = "tab_consumo_final_energetico_fonte", .tipo_dado = "Percentual")
```

:::



### Consumo Final Não Energético por Fonte

::: {.panel-tabset}

## Valor absoluto

```{r}
#| label: tbl-consumo-final-nao-energetico-fonte-absoluto
#| tbl-cap: 'Consumo Final Não Energético por Fonte. Valores absolutos. Unidade: 10³ tep.'

benCorrido::tab_consumo_final_nao_energetico_fonte(con, .tipo = "Absoluto", lang = "en")
benCorrido::gerar_botoes_download(tab_name = "tab_consumo_final_nao_energetico_fonte", .tipo_dado = "Absoluto")
```

## Valor percentual

```{r}
#| label: tbl-consumo-final-nao-energetico-fonte-percentual
#| tbl-cap: 'Consumo Final Não Energético por Fonte. Valores percentuais. Unidade: (%).'

benCorrido::tab_consumo_final_nao_energetico_fonte(con, .tipo = "Percentual", lang = "en")
benCorrido::gerar_botoes_download(tab_name = "tab_consumo_final_nao_energetico_fonte", .tipo_dado = "Percentual")
```

:::


### Dependência Externa de Energia

::: {.panel-tabset}

## Valor absoluto

```{r}
#| label: tbl-dependencia-externa-energia-absoluto
#| tbl-cap: 'Dependência Externa de Energia. Valores absolutos.'

benCorrido::tab_dependencia_externa_energia(con, .tipo = "Absoluto", lang = "en")
benCorrido::gerar_botoes_download(tab_name = "tab_dependencia_externa_energia", .tipo_dado = "Absoluto")
```

## Valor percentual

```{r}
#| label: tbl-dependencia-externa-energia-percentual
#| tbl-cap: 'Dependência Externa de Energia. Valores percentuais. Unidade: (%).'

benCorrido::tab_dependencia_externa_energia(con, .tipo = "Percentual", lang = "en")
benCorrido::gerar_botoes_download(tab_name = "tab_dependencia_externa_energia", .tipo_dado = "Percentual")
```

:::

```{r}
#| fig-height: 4
#| fig-width: 8
#| fig-cap: 'Dependência externa de energia.'
#| label: fig-dependencia-externa-energia
benCorrido::grafico_dependencia_externa_energia(con, lang = "en")
```
