project:
  type: book

profile:
  group: 
    - [pt, en]

execute:
  echo: false
  message: false
  warning: false

number-depth: 2

knitr:
  opts_chunk: 
    fig-width: 5
    fig-height: 2
    out.width: '70%'