project:
  output-dir: ../book

book:
  title: "2024 BRAZILIAN ENERGY BALANCE"
  subtitle: "Base year 2023"
  navbar:
    background: primary
    search: true
    right:
      - text: "Portuguese"
        href: ../livro/index.html
  chapters:
    - text: About
      href: index.qmd
    - en/autoria.qmd
    - part: Chapters
      chapters:
        - en/capitulo_1.qmd
        - en/capitulo_2.qmd
        - en/capitulo_3.qmd
        - en/capitulo_4.qmd
        - en/capitulo_5.qmd
        - en/capitulo_6.qmd
        - en/capitulo_7.qmd
        - en/capitulo_8.qmd
    - part: Appendixes
      chapters:
        - en/anexo_1.qmd
        - en/anexo_2.qmd
        - en/anexo_3.qmd
        - en/anexo_4.qmd
        - en/anexo_5.qmd
        - en/anexo_6.qmd
        - en/anexo_7.qmd
        - en/anexo_8.qmd
        - en/anexo_9.qmd
        - en/anexo_10.qmd
    - text: References
      href: en/referencias.qmd

bibliography: en/referencias.bib

format:
  html:
    theme: cosmo
    css:
      - style.css
      - style-en.css
    smooth-scroll: true
    grid:
      body-width: 1400px
    include-in-header:
      - text: <script src="../js/script.js"></script>

lang: en-US
language:
  crossref-ch-prefix: ""
  crossref-ch-delim: ""

