project:
  output-dir: ../livro

book:
  title: "BALANÇO ENERGÉTICO NACIONAL 2024"
  subtitle: "Ano base 2023"
  navbar:
    background: primary
    search: true
    right:
      - text: "Inglês"
        href: ../book/index.html
  chapters:
    - text: Sobre
      href: index.qmd
    - pt/autoria.qmd
    # - pt/capitulo_1.qmd
    # - pt/capitulo_2.qmd
    - pt/capitulo_3.qmd
    # - pt/anexo_3.qmd
    - text: Referências
      href: pt/referencias.qmd

bibliography: pt/referencias.bib

format:
  html:
    theme: cosmo
    css: 
      - style.css
      - style-pt.css
    smooth-scroll: true
    grid:
      body-width: 1400px

lang: pt-BR
language:
  crossref-ch-prefix: "Capítulo"
