project:
  output-dir: ../book

book:
  title: "2024 BRAZILIAN ENERGY BALANCE"
  subtitle: "Base year 2023"
  navbar:
    background: primary
    search: true
    right:
      - text: "Portuguese"
        href: ../livro/index.html
  chapters:
    - text: About
      href: index.qmd
    - en/autoria-en.qmd
    - en/capitulo_1.qmd
    - text: References
      href: en/referencias.qmd

bibliography: referencias-en.bib

format:
  html:
    theme: cosmo
    css: 
      - style.css
      - style-en.css
    smooth-scroll: true

lang: en
language:
  crossref-ch-prefix: "Chapter"

