project:
  output-dir: ../livro

book:
  title: "BALANÇO ENERGÉTICO NACIONAL 2024"
  subtitle: "Ano base 2023"
  navbar:
    background: primary
    search: true
    right:
      - text: "Inglês"
        href: ../book/index.html
  chapters:
    - text: Sobre
      href: index.qmd
    - pt/autoria.qmd
    - part: Capítulos
      chapters:
        - pt/capitulo_1.qmd
    #     - pt/capitulo_2.qmd
    #     - pt/capitulo_3.qmd
    #     - pt/capitulo_4.qmd
    #     - pt/capitulo_5.qmd
    #     - pt/capitulo_6.qmd
    #     - pt/capitulo_7.qmd
    #     - pt/capitulo_8.qmd
    # - part: Anexos
    #   chapters:
    #     - pt/anexo_1.qmd
    #     - pt/anexo_2.qmd
    #     - pt/anexo_3.qmd
    #     - pt/anexo_4.qmd
    #     - pt/anexo_5.qmd
    #     - pt/anexo_6.qmd
    #     - pt/anexo_7.qmd
    #     - pt/anexo_8.qmd
    #     - pt/anexo_9.qmd
    #     - pt/anexo_10.qmd
    - text: Referências
      href: pt/referencias.qmd

bibliography: pt/referencias.bib

format:
  html:
    theme: cosmo
    css: 
      - style.css
      - style-pt.css
    smooth-scroll: true
    grid:
      body-width: 1400px
    include-in-header:
      - text: <script src="../js/script.js"></script>

lang: pt-BR
language:
  crossref-ch-prefix: ""
  crossref-ch-delim: ""
